//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1094.0 using the following command:
// xscgen C:\Data\Dev\BuildingSmart\IDS\Development\ids.ren.xsd --verbose --netCore --order --nullable --nullableReferenceAttributes --output=C:\Data\Dev\BuildingSmart\IDS\SchemaProject
using Ids;

namespace OldIds
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1094.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("entityType", Namespace="http://standards.buildingsmart.org/IDS")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RequirementsTypeEntity))]
    public partial class EntityType
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("name", Order=0)]
        public IdsValue Name { get; set; }
        
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("predefinedType", Order=1)]
        public IdsValue PredefinedType { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1094.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("idsValue", Namespace="http://standards.buildingsmart.org/IDS")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IdsValue
    {
        
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("simpleValue", Order=0)]
        public string SimpleValue { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Restriction> _restriction;
        
        [System.Xml.Serialization.XmlElementAttribute("restriction", Order=1, Namespace = "http://www.w3.org/2001/XMLSchema")]
        public System.Collections.ObjectModel.Collection<Restriction> Restriction
        {
            get
            {
                return _restriction;
            }
            private set
            {
                _restriction = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Restriction collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RestrictionSpecified
        {
            get
            {
                return (this.Restriction.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="IdsValue" /> class.</para>
        /// </summary>
        public IdsValue()
        {
            this._restriction = new System.Collections.ObjectModel.Collection<Restriction>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1094.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("classificationType", Namespace="http://standards.buildingsmart.org/IDS")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RequirementsTypeClassification))]
    public partial class ClassificationType
    {
        
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("value", Order=0)]
        public IdsValue Value { get; set; }
        
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("system", Order=1)]
        public IdsValue System { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1094.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("partOfType", Namespace="http://standards.buildingsmart.org/IDS")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RequirementsTypePartOf))]
    public partial class PartOfType
    {
        
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("entity", Order=0)]
        public EntityType Entity { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("relation")]
        public Relations Relation { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1094.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("relations", Namespace="http://standards.buildingsmart.org/IDS")]
    public enum Relations
    {
        
        IfcRelAggregates,
        
        IfcRelAssignsToGroup,
        
        IfcRelContainedInSpatialStructure,
        
        IfcRelNests,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1094.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("applicabilityType", Namespace="http://standards.buildingsmart.org/IDS")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ApplicabilityType
    {
        
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("entity", Order=0)]
        public EntityType Entity { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<PartOfType> _partOf;
        
        [System.Xml.Serialization.XmlElementAttribute("partOf", Order=1)]
        public System.Collections.ObjectModel.Collection<PartOfType> PartOf
        {
            get
            {
                return _partOf;
            }
            private set
            {
                _partOf = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the PartOf collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PartOfSpecified
        {
            get
            {
                return (this.PartOf.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="ApplicabilityType" /> class.</para>
        /// </summary>
        public ApplicabilityType()
        {
            this._partOf = new System.Collections.ObjectModel.Collection<PartOfType>();
            this._classification = new System.Collections.ObjectModel.Collection<ClassificationType>();
            this._attribute = new System.Collections.ObjectModel.Collection<AttributeType>();
            this._property = new System.Collections.ObjectModel.Collection<ApplicabilityTypeProperty>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<ClassificationType> _classification;
        
        [System.Xml.Serialization.XmlElementAttribute("classification", Order=2)]
        public System.Collections.ObjectModel.Collection<ClassificationType> Classification
        {
            get
            {
                return _classification;
            }
            private set
            {
                _classification = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Classification collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ClassificationSpecified
        {
            get
            {
                return (this.Classification.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<AttributeType> _attribute;
        
        [System.Xml.Serialization.XmlElementAttribute("attribute", Order=3)]
        public System.Collections.ObjectModel.Collection<AttributeType> Attribute
        {
            get
            {
                return _attribute;
            }
            private set
            {
                _attribute = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Attribute collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AttributeSpecified
        {
            get
            {
                return (this.Attribute.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<ApplicabilityTypeProperty> _property;
        
        [System.Xml.Serialization.XmlElementAttribute("property", Order=4)]
        public System.Collections.ObjectModel.Collection<ApplicabilityTypeProperty> Property
        {
            get
            {
                return _property;
            }
            private set
            {
                _property = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Property collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PropertySpecified
        {
            get
            {
                return (this.Property.Count != 0);
            }
        }
        
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("material", Order=5)]
        public ApplicabilityTypeMaterial Material { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1094.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("attributeType", Namespace="http://standards.buildingsmart.org/IDS")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RequirementsTypeAttribute))]
    public partial class AttributeType
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("name", Order=0)]
        public IdsValue Name { get; set; }
        
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("value", Order=1)]
        public IdsValue Value { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1094.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ApplicabilityTypeProperty", Namespace="http://standards.buildingsmart.org/IDS")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ApplicabilityTypeProperty : PropertyType
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1094.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("propertyType", Namespace="http://standards.buildingsmart.org/IDS")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ApplicabilityTypeProperty))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RequirementsTypeProperty))]
    public partial class PropertyType
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("propertySet", Order=0)]
        public IdsValue PropertySet { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("name", Order=1)]
        public IdsValue Name { get; set; }
        
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("value", Order=2)]
        public IdsValue Value { get; set; }
        
        /// <summary>
        /// <para>This is the name of an IFC Defined Types. See the documentation and default units on https://github.com/buildingSMART/IDS/blob/master/Documentation/Physical_Quantities_and_Units.md</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("This is the name of an IFC Defined Types. See the documentation and default units" +
            " on https://github.com/buildingSMART/IDS/blob/master/Documentation/Physical_Quan" +
            "tities_and_Units.md")]
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("measure")]
        public string Measure { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute("datatype")]
        public string DataType { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1094.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ApplicabilityTypeMaterial", Namespace="http://standards.buildingsmart.org/IDS")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ApplicabilityTypeMaterial : MaterialType
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1094.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("materialType", Namespace="http://standards.buildingsmart.org/IDS")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ApplicabilityTypeMaterial))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RequirementsTypeMaterial))]
    public partial class MaterialType
    {
        
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("value", Order=0)]
        public IdsValue Value { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1094.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("requirementsType", Namespace="http://standards.buildingsmart.org/IDS")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SpecificationTypeRequirements))]
    public partial class RequirementsType
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<RequirementsTypeEntity> _entity;
        
        /// <summary>
        /// <para>Make sure 'Name' value of requirements entity is the same as the 'applicability' node, or a wildcard (inclusive pattern).</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Make sure \'Name\' value of requirements entity is the same as the \'applicability\' " +
            "node, or a wildcard (inclusive pattern).")]
        [System.Xml.Serialization.XmlElementAttribute("entity", Order=0)]
        public System.Collections.ObjectModel.Collection<RequirementsTypeEntity> Entity
        {
            get
            {
                return _entity;
            }
            private set
            {
                _entity = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Entity collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EntitySpecified
        {
            get
            {
                return (this.Entity.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="RequirementsType" /> class.</para>
        /// </summary>
        public RequirementsType()
        {
            this._entity = new System.Collections.ObjectModel.Collection<RequirementsTypeEntity>();
            this._partOf = new System.Collections.ObjectModel.Collection<RequirementsTypePartOf>();
            this._classification = new System.Collections.ObjectModel.Collection<RequirementsTypeClassification>();
            this._attribute = new System.Collections.ObjectModel.Collection<RequirementsTypeAttribute>();
            this._property = new System.Collections.ObjectModel.Collection<RequirementsTypeProperty>();
            this._material = new System.Collections.ObjectModel.Collection<RequirementsTypeMaterial>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<RequirementsTypePartOf> _partOf;
        
        [System.Xml.Serialization.XmlElementAttribute("partOf", Order=1)]
        public System.Collections.ObjectModel.Collection<RequirementsTypePartOf> PartOf
        {
            get
            {
                return _partOf;
            }
            private set
            {
                _partOf = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the PartOf collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PartOfSpecified
        {
            get
            {
                return (this.PartOf.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<RequirementsTypeClassification> _classification;
        
        [System.Xml.Serialization.XmlElementAttribute("classification", Order=2)]
        public System.Collections.ObjectModel.Collection<RequirementsTypeClassification> Classification
        {
            get
            {
                return _classification;
            }
            private set
            {
                _classification = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Classification collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ClassificationSpecified
        {
            get
            {
                return (this.Classification.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<RequirementsTypeAttribute> _attribute;
        
        [System.Xml.Serialization.XmlElementAttribute("attribute", Order=3)]
        public System.Collections.ObjectModel.Collection<RequirementsTypeAttribute> Attribute
        {
            get
            {
                return _attribute;
            }
            private set
            {
                _attribute = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Attribute collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AttributeSpecified
        {
            get
            {
                return (this.Attribute.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<RequirementsTypeProperty> _property;
        
        [System.Xml.Serialization.XmlElementAttribute("property", Order=4)]
        public System.Collections.ObjectModel.Collection<RequirementsTypeProperty> Property
        {
            get
            {
                return _property;
            }
            private set
            {
                _property = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Property collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PropertySpecified
        {
            get
            {
                return (this.Property.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<RequirementsTypeMaterial> _material;
        
        [System.Xml.Serialization.XmlElementAttribute("material", Order=5)]
        public System.Collections.ObjectModel.Collection<RequirementsTypeMaterial> Material
        {
            get
            {
                return _material;
            }
            private set
            {
                _material = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Material collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MaterialSpecified
        {
            get
            {
                return (this.Material.Count != 0);
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1094.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("RequirementsTypeEntity", Namespace="http://standards.buildingsmart.org/IDS")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RequirementsTypeEntity : EntityType
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1094.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("RequirementsTypePartOf", Namespace="http://standards.buildingsmart.org/IDS")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RequirementsTypePartOf : PartOfType, IMinmaxAttributesGroup
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _minOccurs = "1";
        
        [System.ComponentModel.DefaultValueAttribute("1")]
        [System.Xml.Serialization.XmlAttributeAttribute("minOccurs")]
        public string MinOccurs
        {
            get
            {
                return _minOccurs;
            }
            set
            {
                _minOccurs = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _maxOccurs = "1";
        
        /// <summary>
        /// <para>for maxOccurs</para>
        /// </summary>
        [System.ComponentModel.DefaultValueAttribute("1")]
        [System.Xml.Serialization.XmlAttributeAttribute("maxOccurs")]
        public string MaxOccurs
        {
            get
            {
                return _maxOccurs;
            }
            set
            {
                _maxOccurs = value;
            }
        }
        
        /// <summary>
        /// <para>Author of the IDS can leave instructions for the authors of the IFC. This text could/should be displayed in the BIM/IFC authoring tool.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Author of the IDS can leave instructions for the authors of the IFC. This text co" +
            "uld/should be displayed in the BIM/IFC authoring tool.")]
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("instructions")]
        public string Instructions { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1094.0")]
    public partial interface IMinmaxAttributesGroup
    {
        
        [System.ComponentModel.DefaultValueAttribute("1")]
        string MinOccurs
        {
            get;
            set;
        }
        
        /// <summary>
        /// <para>for maxOccurs</para>
        /// </summary>
        [System.ComponentModel.DefaultValueAttribute("1")]
        string MaxOccurs
        {
            get;
            set;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1094.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("RequirementsTypeClassification", Namespace="http://standards.buildingsmart.org/IDS")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RequirementsTypeClassification : ClassificationType, IMinmaxAttributesGroup
    {
        
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("uri")]
        public string Uri { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _minOccurs = "1";
        
        [System.ComponentModel.DefaultValueAttribute("1")]
        [System.Xml.Serialization.XmlAttributeAttribute("minOccurs")]
        public string MinOccurs
        {
            get
            {
                return _minOccurs;
            }
            set
            {
                _minOccurs = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _maxOccurs = "1";
        
        /// <summary>
        /// <para>for maxOccurs</para>
        /// </summary>
        [System.ComponentModel.DefaultValueAttribute("1")]
        [System.Xml.Serialization.XmlAttributeAttribute("maxOccurs")]
        public string MaxOccurs
        {
            get
            {
                return _maxOccurs;
            }
            set
            {
                _maxOccurs = value;
            }
        }
        
        /// <summary>
        /// <para>Author of the IDS can leave instructions for the authors of the IFC. This text could/should be displayed in the BIM/IFC authoring tool.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Author of the IDS can leave instructions for the authors of the IFC. This text co" +
            "uld/should be displayed in the BIM/IFC authoring tool.")]
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("instructions")]
        public string Instructions { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1094.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("RequirementsTypeAttribute", Namespace="http://standards.buildingsmart.org/IDS")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RequirementsTypeAttribute : AttributeType, IMinmaxAttributesGroup
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _minOccurs = "1";
        
        [System.ComponentModel.DefaultValueAttribute("1")]
        [System.Xml.Serialization.XmlAttributeAttribute("minOccurs")]
        public string MinOccurs
        {
            get
            {
                return _minOccurs;
            }
            set
            {
                _minOccurs = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _maxOccurs = "1";
        
        /// <summary>
        /// <para>for maxOccurs</para>
        /// </summary>
        [System.ComponentModel.DefaultValueAttribute("1")]
        [System.Xml.Serialization.XmlAttributeAttribute("maxOccurs")]
        public string MaxOccurs
        {
            get
            {
                return _maxOccurs;
            }
            set
            {
                _maxOccurs = value;
            }
        }
        
        /// <summary>
        /// <para>Author of the IDS can leave instructions for the authors of the IFC. This text could/should be displayed in the BIM/IFC authoring tool.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Author of the IDS can leave instructions for the authors of the IFC. This text co" +
            "uld/should be displayed in the BIM/IFC authoring tool.")]
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("instructions")]
        public string Instructions { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1094.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("RequirementsTypeProperty", Namespace="http://standards.buildingsmart.org/IDS")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RequirementsTypeProperty : PropertyType, IMinmaxAttributesGroup
    {
        
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("uri")]
        public string Uri { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _minOccurs = "1";
        
        [System.ComponentModel.DefaultValueAttribute("1")]
        [System.Xml.Serialization.XmlAttributeAttribute("minOccurs")]
        public string MinOccurs
        {
            get
            {
                return _minOccurs;
            }
            set
            {
                _minOccurs = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _maxOccurs = "1";
        
        /// <summary>
        /// <para>for maxOccurs</para>
        /// </summary>
        [System.ComponentModel.DefaultValueAttribute("1")]
        [System.Xml.Serialization.XmlAttributeAttribute("maxOccurs")]
        public string MaxOccurs
        {
            get
            {
                return _maxOccurs;
            }
            set
            {
                _maxOccurs = value;
            }
        }
        
        /// <summary>
        /// <para>Author of the IDS can leave instructions for the authors of the IFC. This text could/should be displayed in the BIM/IFC authoring tool.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Author of the IDS can leave instructions for the authors of the IFC. This text co" +
            "uld/should be displayed in the BIM/IFC authoring tool.")]
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("instructions")]
        public string Instructions { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1094.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("RequirementsTypeMaterial", Namespace="http://standards.buildingsmart.org/IDS")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RequirementsTypeMaterial : MaterialType, IMinmaxAttributesGroup
    {
        
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("uri")]
        public string Uri { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _minOccurs = "1";
        
        [System.ComponentModel.DefaultValueAttribute("1")]
        [System.Xml.Serialization.XmlAttributeAttribute("minOccurs")]
        public string MinOccurs
        {
            get
            {
                return _minOccurs;
            }
            set
            {
                _minOccurs = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _maxOccurs = "1";
        
        /// <summary>
        /// <para>for maxOccurs</para>
        /// </summary>
        [System.ComponentModel.DefaultValueAttribute("1")]
        [System.Xml.Serialization.XmlAttributeAttribute("maxOccurs")]
        public string MaxOccurs
        {
            get
            {
                return _maxOccurs;
            }
            set
            {
                _maxOccurs = value;
            }
        }
        
        /// <summary>
        /// <para>Author of the IDS can leave instructions for the authors of the IFC. This text could/should be displayed in the BIM/IFC authoring tool.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Author of the IDS can leave instructions for the authors of the IFC. This text co" +
            "uld/should be displayed in the BIM/IFC authoring tool.")]
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("instructions")]
        public string Instructions { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1094.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("specificationType", Namespace="http://standards.buildingsmart.org/IDS")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SpecificationType : IMinmaxAttributesGroup
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("applicability", Order=0)]
        public ApplicabilityType Applicability { get; set; }
        
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("requirements", Order=1)]
        public SpecificationTypeRequirements Requirements { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("name")]
        public string Name { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _minOccurs = "1";
        
        [System.ComponentModel.DefaultValueAttribute("1")]
        [System.Xml.Serialization.XmlAttributeAttribute("minOccurs")]
        public string MinOccurs
        {
            get
            {
                return _minOccurs;
            }
            set
            {
                _minOccurs = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _maxOccurs = "1";
        
        /// <summary>
        /// <para>for maxOccurs</para>
        /// </summary>
        [System.ComponentModel.DefaultValueAttribute("1")]
        [System.Xml.Serialization.XmlAttributeAttribute("maxOccurs")]
        public string MaxOccurs
        {
            get
            {
                return _maxOccurs;
            }
            set
            {
                _maxOccurs = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<string> _ifcVersion;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("ifcVersion")]
        public System.Collections.ObjectModel.Collection<string> IfcVersion
        {
            get
            {
                return _ifcVersion;
            }
            private set
            {
                _ifcVersion = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="SpecificationType" /> class.</para>
        /// </summary>
        public SpecificationType()
        {
            this._ifcVersion = new System.Collections.ObjectModel.Collection<string>();
        }
        
        /// <summary>
        /// <para>Author of the IDS can provide an identifier to the IDS. Beware: this cannot be enforced/assumed as (global) unique.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Author of the IDS can provide an identifier to the IDS. Beware: this cannot be en" +
            "forced/assumed as (global) unique.")]
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("identifier")]
        public string Identifier { get; set; }
        
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("description")]
        public string Description { get; set; }
        
        /// <summary>
        /// <para>Author of the IDS can leave instructions for the authors of the IFC. This text could/should be displayed in the BIM/IFC authoring tool.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Author of the IDS can leave instructions for the authors of the IFC. This text co" +
            "uld/should be displayed in the BIM/IFC authoring tool.")]
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("instructions")]
        public string Instructions { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1094.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("SpecificationTypeRequirements", Namespace="http://standards.buildingsmart.org/IDS")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SpecificationTypeRequirements : RequirementsType
    {
        
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("description")]
        public string Description { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1094.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("specificationsType", Namespace="http://standards.buildingsmart.org/IDS")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IdsSpecifications))]
    public partial class SpecificationsType
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<SpecificationType> _specification;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("specification", Order=0)]
        public System.Collections.ObjectModel.Collection<SpecificationType> Specification
        {
            get
            {
                return _specification;
            }
            private set
            {
                _specification = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="SpecificationsType" /> class.</para>
        /// </summary>
        public SpecificationsType()
        {
            this._specification = new System.Collections.ObjectModel.Collection<SpecificationType>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1094.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ids", Namespace="http://standards.buildingsmart.org/IDS", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("ids", Namespace="http://standards.buildingsmart.org/IDS")]
    public partial class Ids
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("info", Order=0)]
        public IdsInfo Info { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("specifications", Order=1)]
        public IdsSpecifications Specifications { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1094.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("IdsInfo", Namespace="http://standards.buildingsmart.org/IDS", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IdsInfo
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("title", Order=0)]
        public string Title { get; set; }
        
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("copyright", Order=1)]
        public string Copyright { get; set; }
        
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("version", Order=2)]
        public string Version { get; set; }
        
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("description", Order=3)]
        public string Description { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Pattern: [^@]+@[^\.]+\..+.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[^@]+@[^\\.]+\\..+")]
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("author", Order=4)]
        public string Author { get; set; }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("date", Order=5, DataType="date")]
        public System.DateTime DateValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Date property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool DateValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<System.DateTime> Date
        {
            get
            {
                if (this.DateValueSpecified)
                {
                    return this.DateValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.DateValue = value.GetValueOrDefault();
                this.DateValueSpecified = value.HasValue;
            }
        }
        
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("purpose", Order=6)]
        public string Purpose { get; set; }
        
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("milestone", Order=7)]
        public string Milestone { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1094.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("IdsSpecifications", Namespace="http://standards.buildingsmart.org/IDS")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IdsSpecifications : SpecificationsType
    {
    }
}
